version: '3'

services:
  bento4:
    build: .
    ports:
      - "8888:80"
      - "8445:443"
    environment:
      - HTTP_PORT=80
    volumes:
      - ./opt/projects/vod/:/tmp/
    logging:
      driver: splunk
      options:
        splunk-url: "$splunk_url_TS"
        splunk-token: "splunk_token_TS"
        splunk-insecureskipverify: 'true'
        splunk-format: "json"
        splunk-verify-connection: "true"
  ffmpeger:
    build: ./ffmpeg
    volumes:
      - ./opt/projects/vod/:/tmp/
    # Enable logging
#    logging:
#      driver: splunk
#      options:
#        splunk-url: ${splunk_url_TS}
#        splunk-token: ${splunk_token_TS}
#        splunk-insecureskipverify: 'true'
#        splunk-format: "json"
#        splunk-verify-connection: "true"
  web:
    build: ./web
    ports:
      - "8080:80"
      - "8446:443"
    environment:
      - HTTP_PORT=80
    volumes:
      - ./opt/projects/vod/:/tmp/
    # Enable logging
#    logging:
#      driver: splunk
#      options:
#        splunk-url: ${splunk_url_TS}
#        splunk-token: ${splunk_token_TS}
#        splunk-insecureskipverify: 'true'
#        splunk-format: "json"
#        splunk-verify-connection: "true"
volumes:
  sharedA:
    driver: local
    driver_opts:
      type: none
      device: ./opt/projects/vod/
      o: bind